version: '3'
services:
  cassandra:
    image: cassandra:3.0
    ports:
      - "7000:7000"
    environment:
      - CASSANDRA_CLUSTER_NAME=MyCassandraCluster
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack1
    networks:
      - cassandra_network

networks:
  cassandra_network:
    driver: bridge