import { JSONSchemaDataType } from './json-schema.js';

export const CassandraDataType = Object.freeze({
  ASCII: 'ascii',
  BIGINT: 'bigint',
  BOOLEAN: 'boolean',
  COUNTER: 'counter',
  DATE: 'date',
  DECIMAL: 'decimal',
  DOUBLE: 'double',
  FLOAT: 'float',
  INET: 'inet',
  INT: 'int',
  LIST: 'list',
  MAP: 'map',
  SET: 'set',
  SMALLINT: 'smallint',
  TEXT: 'text',
  TIME: 'time',
  TIMESTAMP: 'timestamp',
  TIMEUUID: 'timeuuid',
  TINYINT: 'tinyint',
  TUPLE: 'tuple',
  UUID: 'uuid',
  VARCHAR: 'varchar',
  VARINT: 'varint',
});

export const cassandraToJSONTypeMap = {
  [CassandraDataType.ASCII]: JSONSchemaDataType.STRING,
  [CassandraDataType.BLOB]: JSONSchemaDataType.STRING,
  [CassandraDataType.BOOLEAN]: JSONSchemaDataType.BOOLEAN,
  [CassandraDataType.COUNTER]: JSONSchemaDataType.INTEGER,
  [CassandraDataType.DATE]: JSONSchemaDataType.STRING,
  [CassandraDataType.DECIMAL]: JSONSchemaDataType.NUMBER,
  [CassandraDataType.DOUBLE]: JSONSchemaDataType.NUMBER,
  [CassandraDataType.FLOAT]: JSONSchemaDataType.NUMBER,
  [CassandraDataType.FROZEN]: JSONSchemaDataType.OBJECT,
  [CassandraDataType.INET]: JSONSchemaDataType.STRING,
  [CassandraDataType.INT]: JSONSchemaDataType.INTEGER,
  [CassandraDataType.LIST]: JSONSchemaDataType.ARRAY,
  [CassandraDataType.MAP]: JSONSchemaDataType.OBJECT,
  [CassandraDataType.SET]: JSONSchemaDataType.ARRAY,
  [CassandraDataType.SMALLINT]: JSONSchemaDataType.INTEGER,
  [CassandraDataType.TIMESTAMP]: JSONSchemaDataType.STRING,
  [CassandraDataType.TIME]: JSONSchemaDataType.STRING,
  [CassandraDataType.TIMEUUID]: JSONSchemaDataType.STRING,
  [CassandraDataType.TINYINT]: JSONSchemaDataType.INTEGER,
  [CassandraDataType.TEXT]: JSONSchemaDataType.STRING,
  [CassandraDataType.UUID]: JSONSchemaDataType.STRING,
  [CassandraDataType.VARCHAR]: JSONSchemaDataType.STRING,
  [CassandraDataType.VARINT]: JSONSchemaDataType.INTEGER,
};
