export const CassandraDataType = Object.freeze({
  ASCII: 'ascii',
  BIGINT: 'bigint',
  BOOLEAN: 'boolean',
  COUNTER: 'counter',
  DATE: 'date',
  DECIMAL: 'decimal',
  DOUBLE: 'double',
  FLOAT: 'float',
  INET: 'inet',
  INT: 'int',
  LIST: 'list',
  MAP: 'map',
  SET: 'set',
  SMALLINT: 'smallint',
  TEXT: 'text',
  TIME: 'time',
  TIMESTAMP: 'timestamp',
  TIMEUUID: 'timeuuid',
  TINYINT: 'tinyint',
  TUPLE: 'tuple',
  UUID: 'uuid',
  VARCHAR: 'varchar',
  VARINT: 'varint',
});
